"""
topic_profile.py
================
Manages per-topic filter profiles: strong/support/negative term lists and slot
definitions. A profile can be hand-authored (stored in data/topic_profiles/) or
auto-generated by calling an LLM (OpenAI-compatible API) on first use.

Profile files live at:
    data/topic_profiles/<slug>.json

Schema:
{
  "topic": "居家健身",
  "generated_at": "2026-07-16T...",
  "source": "ai" | "builtin",
  "strong_terms":   ["..."],   // strong positive signals (in title or desc)
  "support_terms":  ["..."],   // soft positive signals (≥2 needed)
  "hard_negative":  ["..."],   // always reject if present
  "soft_negative":  ["..."],   // reject if in title and no strong signal
  "slots": [
    {"title": "...", "intent": "...", "keywords": ["..."]}
  ]
}
"""
from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

from .models import Slot, slugify


# ---------------------------------------------------------------------------
# Built-in profiles for common Bilibili arrangement domains
# ---------------------------------------------------------------------------
_COMMON_HARD_NEGATIVE = [
    "档位", "课程介绍", "合集介绍", "购买链接", "训练营招生", "私教课",
    "会员专享", "试看", "直播回放", "公告", "抽奖",
]

_COMMON_SOFT_NEGATIVE = [
    "介绍", "说明", "为什么", "怎么选", "区别", "合集", "预告", "直播", "回放",
    "日常", "vlog", "聊聊", "分享", "心得", "测评", "采访", "故事", "通知", "复盘",
]


def _builtin_profile(
    topic: str,
    strong_terms: List[str],
    support_terms: List[str],
    slots: List[Dict[str, Any]],
    hard_negative: Optional[List[str]] = None,
    soft_negative: Optional[List[str]] = None,
    filter_dimensions: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    return {
        "topic": topic,
        "source": "builtin",
        "strong_terms": strong_terms,
        "support_terms": support_terms,
        "hard_negative": hard_negative if hard_negative is not None else list(_COMMON_HARD_NEGATIVE),
        "soft_negative": soft_negative if soft_negative is not None else list(_COMMON_SOFT_NEGATIVE),
        "filter_dimensions": filter_dimensions or {},
        "slots": slots,
    }


# ---------------------------------------------------------------------------
# Shared filter dimension definitions
# ---------------------------------------------------------------------------
_DIM_MOVEMENT_COMMON = {
    "space": {
        "站立": ["站立", "站着练", "全程站立", "站立训练"],
        "坐姿": ["坐姿", "坐着练", "椅子", "凳子", "坐凳"],
        "垫上": ["垫上", "瑜伽垫", "垫子", "地面"],
        "床上": ["床上", "睡前床上"],
    },
    "body_part": {
        "肩颈": ["肩颈", "颈椎", "肩膀", "颈部", "斜方肌"],
        "腰背": ["腰背", "腰部", "背部", "脊柱", "下背", "腰椎"],
        "核心": ["核心", "腹部", "腹肌", "马甲线"],
        "臀腿": ["臀腿", "臀部", "腿部", "髋", "下肢", "大腿", "小腿"],
        "上肢": ["上肢", "手臂", "肩背", "背部"],
        "全身": ["全身", "整体", "综合", "全面"],
    },
    "intensity": {
        "低强度": ["低强度", "温和", "舒缓", "放松", "修复", "恢复", "轻柔"],
        "中等强度": ["中等", "适度", "流动", "平衡"],
        "高强度": ["高强度", "燃脂", "暴汗", "力量", "爆发"],
    },
    "movement": {
        "跳跃": ["跳跃", "蹦跳", "跳"],
        "深蹲": ["深蹲", "蹲"],
        "平板": ["平板支撑", "平板", "plank"],
        "倒立": ["倒立", "头倒立", "手倒立"],
        "后弯": ["后弯", "下腰"],
    },
    "audience": {
        "新手": ["新手", "初学者", "入门", "零基础", "基础"],
        "进阶": ["进阶", "高级", "挑战"],
        "经期": ["经期", "生理期", "姨妈期"],
        "膝盖友好": ["膝盖友好", "膝盖不好", "膝盖不适", "保护膝盖"],
        "腰部友好": ["腰部友好", "腰不好", "腰疼", "腰间盘"],
    },
    "time_of_day": {
        "晨间": ["晨间", "早晨", "清晨", "早起", "早上"],
        "晚间": ["晚间", "晚上", "睡前", "夜晚", "夜间", "入夜", "夜里"],
    },
}

_DIM_EQUIPMENT = {
    "无器械": ["无器械", "无工具", "徒手", "无需器械", "不用器械"],
    "弹力带": ["弹力带", "阻力带", "伸展带"],
    "瑜伽砖": ["瑜伽砖", "砖"],
    "泡沫轴": ["泡沫轴", "滚轴"],
    "哑铃": ["哑铃", "壶铃"],
}

_DIM_MOVEMENT = dict(_DIM_MOVEMENT_COMMON, equipment=_DIM_EQUIPMENT)

_DIM_MEDITATION = {
    "position": {
        "坐姿": ["坐姿", "坐着", "椅子", "凳"],
        "躺姿": ["躺姿", "躺着", "卧姿", "仰卧", "平躺"],
        "行走": ["行走", "步行冥想", "走路"],
    },
    "guidance": {
        "引导冥想": ["引导冥想", "引导", "带领", "口令"],
        "纯音乐": ["纯音乐", "无引导", "无语音"],
        "白噪音": ["白噪音", "白噪声"],
        "身体扫描": ["身体扫描", "扫描"],
        "呼吸练习": ["呼吸练习", "观呼吸", "呼吸法"],
        "内观": ["内观", "正念", "觉察"],
    },
    "purpose": {
        "放松": ["放松", "舒缓", "平静"],
        "助眠": ["助眠", "睡眠", "入睡", "安睡"],
        "专注": ["专注", "注意力", "集中"],
        "焦虑缓解": ["焦虑", "压力", "紧张"],
        "情绪释放": ["情绪", "释放", "疗愈"],
    },
    "voice": {
        "中文引导": ["中文", "国语"],
        "英文引导": ["英文", "英语", "english"],
        "无语音": ["无语音", "无引导", "纯音乐"],
    },
    "time_of_day": _DIM_MOVEMENT_COMMON["time_of_day"],
}

_DIM_HEALING_MUSIC = {
    "sound_type": {
        "轻音乐": ["轻音乐", "轻柔", "舒缓"],
        "白噪音": ["白噪音", "白噪声"],
        "自然音": ["自然音", "自然声"],
        "颂钵": ["颂钵", "音钵", "sound bath"],
        "频率音乐": ["432hz", "528hz", "频率"],
        "纯音乐": ["纯音乐", "器乐", "无歌词"],
        "环境音": ["环境音", "氛围"],
        "ASMR": ["asmr", "助眠音"],
    },
    "purpose": {
        "放松": ["放松", "舒缓", "减压"],
        "助眠": ["助眠", "睡眠", "安睡", "入睡"],
        "专注": ["专注", "学习", "工作"],
        "冥想背景": ["冥想", "背景"],
    },
    "has_lyrics": {
        "纯器乐": ["纯音乐", "无歌词", "纯器乐", "无唱词"],
        "有人声": ["有人声", "演唱", "歌唱"],
    },
    "environment": {
        "雨声": ["雨声", "雨"],
        "海浪": ["海浪", "海洋", "海水"],
        "森林": ["森林", "树林", "鸟鸣"],
    },
    "time_of_day": _DIM_MOVEMENT_COMMON["time_of_day"],
}

_DIM_SLEEP = {
    "method": {
        "音乐": ["音乐", "轻音乐", "纯音乐"],
        "白噪音": ["白噪音", "白噪声"],
        "冥想": ["冥想", "引导冥想"],
        "拉伸": ["拉伸", "放松训练"],
        "ASMR": ["asmr"],
    },
    "position": _DIM_MEDITATION["position"],
    "environment": _DIM_HEALING_MUSIC["environment"],
    "time_of_day": _DIM_MOVEMENT_COMMON["time_of_day"],
}

_DIM_COOKING = {
    "meal_type": {
        "早餐": ["早餐", "早饭"],
        "快手菜": ["快手", "快速", "简单"],
        "正餐": ["正餐", "下饭", "晚餐", "午餐"],
        "便当": ["便当", "带饭", "meal prep"],
        "烘焙": ["烘焙", "面包", "蛋糕"],
        "汤粥": ["汤", "粥", "煲汤"],
    },
    "difficulty": {
        "新手": ["新手", "简单", "零基础"],
        "进阶": ["进阶", "硬菜", "复杂"],
    },
    "tool": {
        "空气炸锅": ["空气炸锅"],
        "电饭煲": ["电饭煲"],
        "烤箱": ["烤箱"],
    },
    "diet": {
        "低卡": ["低卡", "减脂", "低脂"],
        "高蛋白": ["高蛋白", "蛋白质"],
        "素食": ["素食", "素"],
        "家常": ["家常", "家常菜"],
    },
}

_DIM_KNOWLEDGE = {
    "difficulty": {
        "入门": ["入门", "零基础", "新手", "基础"],
        "进阶": ["进阶", "高级", "深度", "专业"],
    },
    "content_type": {
        "教程": ["教程", "教学", "讲解"],
        "实战": ["实战", "项目", "案例", "实操"],
        "科普": ["科普", "介绍", "概览"],
    },
}

_DIM_PROGRAMMING = dict(_DIM_KNOWLEDGE)
_DIM_PROGRAMMING["language"] = {
    "Python": ["python"],
    "JavaScript": ["javascript", "js", "前端"],
    "Java": ["java"],
    "Go": ["go", "golang"],
}
_DIM_FINANCE = dict(_DIM_KNOWLEDGE)
_DIM_FINANCE["topic_area"] = {
    "基金": ["基金", "定投", "指数基金", "etf"],
    "股票": ["股票", "个股", "股市"],
    "宏观": ["宏观", "经济", "周期"],
    "财报": ["财报", "财务", "估值"],
    "理财": ["理财", "规划", "资产配置"],
}
_DIM_SCIENCE = dict(_DIM_KNOWLEDGE)
_DIM_SCIENCE["field"] = {
    "科学": ["科学", "自然", "物理", "生物"],
    "历史": ["历史", "古代", "近代"],
    "心理": ["心理", "认知", "行为"],
    "商业": ["商业", "商业分析", "行业"],
    "社科": ["社科", "社会", "人文"],
}


_BUILTIN_YOGA = _builtin_profile(
    "瑜伽",
    [
        "跟练", "follow along", "workout", "flow", "流瑜伽", "瑜伽流", "阴瑜伽",
        "拉伸", "伸展", "开髋", "唤醒", "修复", "放松", "舒缓", "热身",
        "燃脂", "塑形", "核心", "肩颈", "腰背", "下肢", "全身", "调理", "训练",
        "晨间", "早晨", "清晨", "睡前", "晚间", "初学者", "新手", "入门", "完整", "全套",
    ],
    ["瑜伽", "yoga", "练习", "体式", "呼吸", "冥想", "理疗", "居家", "分钟", "min", "stretch", "mobility"],
    [
        {"title": "晨间唤醒", "intent": "用低门槛练习打开身体，避免一开始就太重。", "keywords": ["晨间", "唤醒", "热身", "舒展", "流动"]},
        {"title": "核心稳定", "intent": "让一周里有一点力量和控制感。", "keywords": ["核心", "腹部", "稳定", "力量"]},
        {"title": "肩颈修复", "intent": "照顾久坐和上半身紧张。", "keywords": ["肩颈", "颈椎", "放松", "修复", "久坐"]},
        {"title": "流动燃脂", "intent": "安排稍有节奏感的流动练习。", "keywords": ["流动", "燃脂", "全身", "塑形", "流瑜伽"]},
        {"title": "髋腿拉伸", "intent": "补足髋部、腿后侧和下肢活动度。", "keywords": ["开髋", "髋", "腿", "拉伸", "下肢"]},
        {"title": "完整跟练", "intent": "周末放一个更完整的视频。", "keywords": ["完整", "全套", "进阶", "长练", "连贯"]},
        {"title": "睡前恢复", "intent": "最后一天降低强度，用放松收尾。", "keywords": ["睡前", "放松", "冥想", "阴瑜伽", "恢复"]},
    ],
    hard_negative=["档位", "答疑", "练习答疑", "课程介绍", "合集介绍", "使用说明", "自我介绍", "直播回放"],
    filter_dimensions=_DIM_MOVEMENT,
)

_BUILTIN_MEDITATION = _builtin_profile(
    "冥想",
    ["冥想引导", "引导冥想", "正念冥想", "呼吸冥想", "身体扫描", "观呼吸", "静心", "放松冥想", "睡前冥想", "晨间冥想", "情绪释放", "内观", "慈心冥想", "疗愈冥想", "10分钟冥想"],
    ["冥想", "meditation", "正念", "呼吸", "觉察", "放松", "专注", "平静", "焦虑", "压力", "睡前", "晨间", "引导", "练习"],
    [
        {"title": "短时进入", "intent": "用短引导降低开始成本。", "keywords": ["5分钟", "10分钟", "入门", "引导"]},
        {"title": "呼吸稳定", "intent": "用呼吸练习稳定注意力。", "keywords": ["呼吸", "观呼吸", "专注", "觉察"]},
        {"title": "身体扫描", "intent": "把注意力带回身体感受。", "keywords": ["身体扫描", "放松", "躯体", "觉察"]},
        {"title": "情绪安顿", "intent": "安排处理焦虑、压力或杂念的内容。", "keywords": ["焦虑", "压力", "情绪", "平静"]},
        {"title": "晨间清醒", "intent": "用清晨练习建立一天的节奏。", "keywords": ["晨间", "清晨", "唤醒", "能量"]},
        {"title": "深度静心", "intent": "周末放一个更完整的冥想练习。", "keywords": ["深度", "完整", "30分钟", "内观"]},
        {"title": "睡前收束", "intent": "用睡前冥想结束一周。", "keywords": ["睡前", "放松", "助眠", "安睡"]},
    ],
    filter_dimensions=_DIM_MEDITATION,
)

_BUILTIN_HOME_FITNESS = _builtin_profile(
    "居家健身",
    ["居家跟练", "无器械", "徒手训练", "全身燃脂", "hiit", "低冲击", "帕梅拉", "tabata", "核心训练", "臀腿训练", "上肢训练", "腹肌训练", "热身", "拉伸放松", "新手友好", "站立训练", "不跳"],
    ["健身", "workout", "训练", "跟练", "燃脂", "塑形", "居家", "分钟", "无跳跃", "低噪音", "新手", "全身", "核心", "有氧"],
    [
        {"title": "热身启动", "intent": "先激活身体，降低受伤风险。", "keywords": ["热身", "激活", "新手", "低强度"]},
        {"title": "低冲击有氧", "intent": "安排不扰民、可持续的有氧。", "keywords": ["低冲击", "不跳", "低噪音", "有氧"]},
        {"title": "核心控制", "intent": "补足核心稳定和腹部训练。", "keywords": ["核心", "腹肌", "稳定", "平板"]},
        {"title": "臀腿力量", "intent": "安排下肢和臀腿塑形。", "keywords": ["臀腿", "下肢", "深蹲", "臀部"]},
        {"title": "上肢耐力", "intent": "让肩背手臂也有适量参与。", "keywords": ["上肢", "手臂", "肩背", "背部"]},
        {"title": "全身循环", "intent": "用全身训练承接一周积累。", "keywords": ["全身", "循环", "燃脂", "hiit"]},
        {"title": "拉伸恢复", "intent": "最后用拉伸和放松收尾。", "keywords": ["拉伸", "放松", "恢复", "筋膜"]},
    ],
    filter_dimensions=_DIM_MOVEMENT,
)

_BUILTIN_HEALING_MUSIC = _builtin_profile(
    "疗愈音乐",
    ["疗愈音乐", "轻音乐", "冥想音乐", "助眠音乐", "白噪音", "自然音", "雨声", "海浪声", "颂钵", "sound bath", "432hz", "528hz", "放松音乐", "睡眠音乐", "学习音乐", "环境音"],
    ["音乐", "music", "放松", "疗愈", "助眠", "冥想", "专注", "白噪", "雨声", "海浪", "自然", "轻柔", "纯音乐", "氛围"],
    [
        {"title": "轻柔进入", "intent": "先选低存在感、容易进入状态的音乐。", "keywords": ["轻音乐", "放松", "舒缓", "纯音乐"]},
        {"title": "专注背景", "intent": "安排适合工作或学习的背景音。", "keywords": ["学习", "专注", "工作", "背景音乐"]},
        {"title": "自然环境", "intent": "用自然声降低信息刺激。", "keywords": ["雨声", "海浪", "森林", "自然音"]},
        {"title": "情绪舒缓", "intent": "安排偏情绪安抚的疗愈音乐。", "keywords": ["疗愈", "舒缓", "焦虑", "平静"]},
        {"title": "冥想陪伴", "intent": "给冥想或呼吸练习配背景。", "keywords": ["冥想", "颂钵", "432hz", "528hz"]},
        {"title": "长时氛围", "intent": "周末安排更长时段的氛围音。", "keywords": ["1小时", "3小时", "长时间", "环境音"]},
        {"title": "睡前助眠", "intent": "用更慢、更暗的声音收尾。", "keywords": ["助眠", "睡眠", "睡前", "白噪音"]},
    ],
    hard_negative=["翻唱", "演唱会", "mv", "reaction", "乐评", "专辑介绍", "直播回放", "购买链接"],
    filter_dimensions=_DIM_HEALING_MUSIC,
)

_BUILTIN_PILATES = _builtin_profile(
    "普拉提",
    ["普拉提跟练", "垫上普拉提", "mat pilates", "pilates", "核心普拉提", "普拉提入门", "骨盆稳定", "呼吸控制", "臀腿塑形", "腰腹训练", "肩背改善", "体态矫正", "全身普拉提", "新手普拉提"],
    ["普拉提", "核心", "垫上", "体态", "塑形", "呼吸", "稳定", "跟练", "分钟", "新手", "腰腹", "臀腿"],
    [
        {"title": "基础呼吸", "intent": "先建立呼吸和核心连接。", "keywords": ["呼吸", "基础", "入门", "核心"]},
        {"title": "骨盆稳定", "intent": "安排骨盆和腰腹控制练习。", "keywords": ["骨盆", "稳定", "腰腹", "控制"]},
        {"title": "核心塑形", "intent": "强化腹部和深层核心。", "keywords": ["核心", "腹部", "马甲线", "腰腹"]},
        {"title": "臀腿线条", "intent": "补足臀腿激活和下肢塑形。", "keywords": ["臀腿", "臀部", "腿部", "下肢"]},
        {"title": "肩背体态", "intent": "照顾圆肩驼背和肩背紧张。", "keywords": ["肩背", "体态", "圆肩", "驼背"]},
        {"title": "全身串联", "intent": "安排完整垫上普拉提。", "keywords": ["全身", "完整", "垫上", "进阶"]},
        {"title": "放松拉伸", "intent": "以温和拉伸结束一周。", "keywords": ["拉伸", "放松", "舒缓", "恢复"]},
    ],
    filter_dimensions=_DIM_MOVEMENT,
)

_BUILTIN_RUNNING = _builtin_profile(
    "跑步训练",
    ["跑步训练", "跑姿", "跑步入门", "有氧基础", "间歇跑", "节奏跑", "慢跑", "配速", "心率跑", "跑前热身", "跑后拉伸", "5公里", "10公里", "马拉松", "跑步力量", "跑步计划"],
    ["跑步", "running", "慢跑", "有氧", "配速", "心率", "跑姿", "热身", "拉伸", "耐力", "训练", "公里", "马拉松"],
    [
        {"title": "入门基础", "intent": "先建立跑步基础概念和安全边界。", "keywords": ["入门", "新手", "基础", "跑步计划"]},
        {"title": "跑前热身", "intent": "补齐热身和动态激活。", "keywords": ["跑前", "热身", "动态拉伸", "激活"]},
        {"title": "跑姿效率", "intent": "安排跑姿、步频或落地方式内容。", "keywords": ["跑姿", "步频", "落地", "效率"]},
        {"title": "有氧耐力", "intent": "安排慢跑、心率或耐力基础。", "keywords": ["慢跑", "心率", "有氧", "耐力"]},
        {"title": "间歇提升", "intent": "加入一点速度和节奏训练。", "keywords": ["间歇", "节奏跑", "配速", "速度"]},
        {"title": "力量辅助", "intent": "用力量训练支持跑步表现。", "keywords": ["力量", "臀腿", "核心", "跑步力量"]},
        {"title": "跑后恢复", "intent": "用拉伸和恢复内容收尾。", "keywords": ["跑后", "拉伸", "恢复", "放松"]},
    ],
    filter_dimensions=_DIM_MOVEMENT,
)

_BUILTIN_FAT_LOSS = _builtin_profile(
    "减脂塑形",
    ["减脂跟练", "燃脂训练", "减脂餐", "热量缺口", "低冲击燃脂", "全身燃脂", "hiit燃脂", "力量塑形", "体脂率", "瘦全身", "瘦腰腹", "臀腿塑形", "饮食控制", "新手减脂", "不节食"],
    ["减脂", "燃脂", "塑形", "瘦身", "训练", "饮食", "热量", "蛋白质", "有氧", "力量", "跟练", "体脂", "低卡"],
    [
        {"title": "建立原则", "intent": "先安排减脂原则，避免只看单次消耗。", "keywords": ["热量缺口", "原则", "入门", "误区"]},
        {"title": "低冲击燃脂", "intent": "安排可坚持、不扰民的燃脂训练。", "keywords": ["低冲击", "不跳", "燃脂", "有氧"]},
        {"title": "力量塑形", "intent": "补足力量训练，避免只做有氧。", "keywords": ["力量", "塑形", "臀腿", "核心"]},
        {"title": "饮食搭配", "intent": "安排低卡、高蛋白或备餐内容。", "keywords": ["减脂餐", "低卡", "蛋白质", "备餐"]},
        {"title": "全身循环", "intent": "用全身训练提高整体消耗。", "keywords": ["全身", "循环", "hiit", "燃脂"]},
        {"title": "局部强化", "intent": "安排腰腹、臀腿等塑形重点。", "keywords": ["腰腹", "臀腿", "手臂", "线条"]},
        {"title": "恢复坚持", "intent": "用恢复和复盘内容帮助长期执行。", "keywords": ["拉伸", "恢复", "坚持", "复盘"]},
    ],
    soft_negative=_COMMON_SOFT_NEGATIVE + ["暴瘦", "七天瘦", "三天瘦", "节食", "代餐广告"],
    filter_dimensions=_DIM_MOVEMENT,
)

_BUILTIN_SLEEP = _builtin_profile(
    "睡眠助眠",
    ["助眠", "睡前放松", "睡眠音乐", "白噪音", "雨声助眠", "冥想助眠", "身体扫描", "睡前拉伸", "放松训练", "呼吸放松", "催眠引导", "失眠缓解", "安睡", "深度睡眠", "asmr助眠"],
    ["睡眠", "睡前", "失眠", "放松", "冥想", "呼吸", "白噪", "雨声", "asmr", "安眠", "舒缓", "夜晚", "入睡"],
    [
        {"title": "环境降噪", "intent": "先用白噪或自然声降低外部刺激。", "keywords": ["白噪音", "雨声", "自然音", "环境音"]},
        {"title": "呼吸放松", "intent": "安排睡前呼吸练习。", "keywords": ["呼吸", "放松", "睡前", "引导"]},
        {"title": "身体扫描", "intent": "用身体扫描释放紧张。", "keywords": ["身体扫描", "肌肉放松", "紧张", "释放"]},
        {"title": "睡前拉伸", "intent": "安排低强度身体放松内容。", "keywords": ["睡前拉伸", "拉伸", "肩颈", "腰背"]},
        {"title": "冥想助眠", "intent": "用冥想引导进入睡眠。", "keywords": ["冥想", "助眠", "引导", "安睡"]},
        {"title": "长时陪伴", "intent": "准备更长的睡眠背景音。", "keywords": ["1小时", "8小时", "长时间", "睡眠音乐"]},
        {"title": "深度安睡", "intent": "用最弱刺激内容收尾。", "keywords": ["深度睡眠", "安睡", "催眠", "舒缓"]},
    ],
    hard_negative=["鬼故事", "恐怖", "惊悚", "reaction", "直播回放", "广告", "购买链接"],
    filter_dimensions=_DIM_SLEEP,
)

_BUILTIN_STRETCHING = _builtin_profile(
    "拉伸恢复",
    ["拉伸跟练", "全身拉伸", "睡前拉伸", "晨间拉伸", "肩颈拉伸", "腰背放松", "髋部拉伸", "腿部拉伸", "泡沫轴", "筋膜放松", "运动后拉伸", "恢复训练", "灵活性", "开髋", "久坐放松"],
    ["拉伸", "stretch", "恢复", "放松", "筋膜", "肩颈", "腰背", "髋", "腿", "久坐", "柔韧", "活动度", "mobility"],
    [
        {"title": "全身舒展", "intent": "先用全身拉伸打开身体。", "keywords": ["全身", "舒展", "拉伸", "放松"]},
        {"title": "肩颈释放", "intent": "照顾久坐后的肩颈紧张。", "keywords": ["肩颈", "颈椎", "斜方肌", "久坐"]},
        {"title": "腰背放松", "intent": "安排腰背和脊柱相关恢复。", "keywords": ["腰背", "脊柱", "下背", "放松"]},
        {"title": "髋腿活动", "intent": "补足髋部和腿后侧活动度。", "keywords": ["开髋", "髋部", "腿后侧", "下肢"]},
        {"title": "筋膜放松", "intent": "加入泡沫轴或筋膜释放内容。", "keywords": ["泡沫轴", "筋膜", "放松", "按摩"]},
        {"title": "运动后恢复", "intent": "安排训练后的恢复拉伸。", "keywords": ["运动后", "恢复", "拉伸", "放松"]},
        {"title": "睡前舒缓", "intent": "以低刺激睡前拉伸结束一周。", "keywords": ["睡前", "舒缓", "放松", "拉伸"]},
    ],
    filter_dimensions=_DIM_MOVEMENT,
)

_BUILTIN_COOKING = _builtin_profile(
    "烹饪食谱",
    ["家常菜教程", "快手菜", "一人食", "减脂餐", "低卡食谱", "早餐教程", "便当", "备餐", "空气炸锅", "电饭煲", "下饭菜", "汤", "面食", "烘焙教程", "新手做饭", "健康饮食"],
    ["做饭", "烹饪", "食谱", "教程", "家常菜", "厨房", "食材", "早餐", "午餐", "晚餐", "低卡", "健康", "备餐", "菜谱"],
    [
        {"title": "新手入门", "intent": "先安排步骤清楚、容错高的菜谱。", "keywords": ["新手", "简单", "家常", "教程"]},
        {"title": "快手正餐", "intent": "安排工作日可执行的快手菜。", "keywords": ["快手菜", "一人食", "晚餐", "下饭菜"]},
        {"title": "健康轻食", "intent": "补充低卡或营养搭配内容。", "keywords": ["低卡", "减脂餐", "健康", "蛋白质"]},
        {"title": "早餐便当", "intent": "安排早餐、便当或备餐。", "keywords": ["早餐", "便当", "备餐", "meal prep"]},
        {"title": "厨房工具", "intent": "用空气炸锅、电饭煲等降低操作成本。", "keywords": ["空气炸锅", "电饭煲", "烤箱", "锅"]},
        {"title": "周末进阶", "intent": "周末安排更完整或稍复杂的食谱。", "keywords": ["烘焙", "面食", "硬菜", "完整"]},
        {"title": "汤粥收尾", "intent": "用温和、易消化内容收尾。", "keywords": ["汤", "粥", "清淡", "养胃"]},
    ],
    hard_negative=["探店", "吃播", "试吃", "开箱", "团购", "商单", "直播回放", "购买链接"],
    filter_dimensions=_DIM_COOKING,
)

_BUILTIN_STUDY = _builtin_profile(
    "学习方法",
    ["学习方法", "高效学习", "study with me", "自习室", "时间管理", "番茄钟", "记忆方法", "笔记方法", "复习计划", "考试规划", "专注力", "拖延症", "anki", "obsidian", "知识管理", "学习规划"],
    ["学习", "自习", "效率", "复习", "笔记", "记忆", "专注", "计划", "考试", "方法", "时间管理", "study", "规划"],
    [
        {"title": "目标拆解", "intent": "先明确学习目标和计划框架。", "keywords": ["规划", "目标", "计划", "入门"]},
        {"title": "专注陪伴", "intent": "安排 study with me 或番茄钟内容。", "keywords": ["study with me", "自习", "番茄钟", "专注"]},
        {"title": "笔记系统", "intent": "安排笔记、整理或知识管理方法。", "keywords": ["笔记", "obsidian", "知识管理", "整理"]},
        {"title": "记忆复习", "intent": "补充记忆和间隔复习。", "keywords": ["记忆", "anki", "复习", "背诵"]},
        {"title": "拖延处理", "intent": "安排执行和反拖延内容。", "keywords": ["拖延", "执行力", "习惯", "自律"]},
        {"title": "考试冲刺", "intent": "安排考试或阶段性冲刺方法。", "keywords": ["考试", "冲刺", "复盘", "刷题"]},
        {"title": "周末复盘", "intent": "用复盘内容帮助调整下周计划。", "keywords": ["复盘", "总结", "调整", "计划"]},
    ],
    filter_dimensions=_DIM_KNOWLEDGE,
)

_BUILTIN_PROGRAMMING = _builtin_profile(
    "编程开发",
    ["编程教程", "零基础入门", "python教程", "前端教程", "javascript", "java教程", "go语言", "算法", "数据结构", "项目实战", "代码实战", "环境配置", "debug", "源码讲解", "面试题", "全栈开发", "ai编程"],
    ["编程", "开发", "代码", "教程", "python", "javascript", "java", "前端", "后端", "算法", "项目", "实战", "程序员", "入门"],
    [
        {"title": "环境准备", "intent": "先安排安装、环境和基础工具。", "keywords": ["环境配置", "安装", "入门", "工具"]},
        {"title": "语法基础", "intent": "补齐语言基础和核心语法。", "keywords": ["语法", "基础", "零基础", "变量"]},
        {"title": "核心概念", "intent": "安排函数、对象、模块等核心概念。", "keywords": ["函数", "对象", "模块", "核心"]},
        {"title": "项目实战", "intent": "用实战项目把知识串起来。", "keywords": ["项目", "实战", "案例", "从0到1"]},
        {"title": "调试排错", "intent": "安排 debug、报错和工程习惯内容。", "keywords": ["debug", "报错", "调试", "排错"]},
        {"title": "算法面试", "intent": "补充数据结构、算法或面试题。", "keywords": ["算法", "数据结构", "面试", "刷题"]},
        {"title": "完整路线", "intent": "用路线图或体系课收尾。", "keywords": ["路线", "体系", "全套", "进阶"]},
    ],
    hard_negative=["卖课", "培训班", "领取资料", "加群", "资料分享", "网盘", "直播回放", "购买链接"],
    filter_dimensions=_DIM_PROGRAMMING,
)

_BUILTIN_FINANCE = _builtin_profile(
    "财经投资",
    ["财经分析", "投资入门", "基金定投", "资产配置", "股票基础", "财报分析", "宏观经济", "行业分析", "商业模式", "估值", "指数基金", "理财规划", "风险控制", "复盘", "市场解读"],
    ["财经", "投资", "理财", "基金", "股票", "债券", "经济", "宏观", "行业", "财报", "估值", "风险", "资产", "配置"],
    [
        {"title": "基础概念", "intent": "先安排投资和理财基础概念。", "keywords": ["入门", "基础", "理财", "投资"]},
        {"title": "风险框架", "intent": "补足风险、仓位和资产配置。", "keywords": ["风险", "仓位", "资产配置", "回撤"]},
        {"title": "基金指数", "intent": "安排基金、指数或定投内容。", "keywords": ["基金", "指数基金", "定投", "etf"]},
        {"title": "公司财报", "intent": "安排财报和商业模式分析。", "keywords": ["财报", "商业模式", "公司", "估值"]},
        {"title": "宏观行业", "intent": "补充宏观和行业视角。", "keywords": ["宏观", "行业", "经济", "周期"]},
        {"title": "市场复盘", "intent": "安排近期市场解读和复盘。", "keywords": ["市场", "复盘", "解读", "行情"]},
        {"title": "长期规划", "intent": "用长期理财规划内容收尾。", "keywords": ["规划", "长期", "养老", "资产"]},
    ],
    hard_negative=["荐股", "带单", "稳赚", "暴富", "内幕", "群", "直播回放", "购买链接"],
    soft_negative=_COMMON_SOFT_NEGATIVE + ["今日涨停", "妖股", "短线密码", "翻倍"],
    filter_dimensions=_DIM_FINANCE,
)

_BUILTIN_SCIENCE = _builtin_profile(
    "知识科普",
    ["科普", "科学科普", "社科人文", "历史科普", "心理学", "认知科学", "商业分析", "行业分析", "纪录片", "深度解析", "硬核科普", "通俗讲解", "公开课", "讲座", "知识区", "读书分享"],
    ["知识", "科普", "科学", "历史", "人文", "心理", "社会", "商业", "行业", "讲解", "解析", "公开课", "纪录片", "读书"],
    [
        {"title": "轻量入门", "intent": "先安排容易进入的通俗内容。", "keywords": ["入门", "通俗", "基础", "科普"]},
        {"title": "核心概念", "intent": "安排主题里的关键概念讲解。", "keywords": ["概念", "原理", "解释", "讲解"]},
        {"title": "案例拆解", "intent": "用具体案例承接抽象知识。", "keywords": ["案例", "拆解", "故事", "分析"]},
        {"title": "跨学科视角", "intent": "安排人文、科技或社会的交叉视角。", "keywords": ["人文", "科技", "社会", "心理"]},
        {"title": "行业观察", "intent": "加入行业或现实议题内容。", "keywords": ["行业", "商业", "趋势", "观察"]},
        {"title": "深度长内容", "intent": "周末留给更完整的信息密度。", "keywords": ["深度", "纪录片", "长视频", "公开课"]},
        {"title": "读书补充", "intent": "用书籍或资料型内容补全。", "keywords": ["读书", "书单", "资料", "推荐"]},
    ],
    filter_dimensions=_DIM_SCIENCE,
)

_BUILTIN_PROFILES: Dict[str, Dict[str, Any]] = {
    "yoga": _BUILTIN_YOGA,
    "meditation": _BUILTIN_MEDITATION,
    "home_fitness": _BUILTIN_HOME_FITNESS,
    "healing_music": _BUILTIN_HEALING_MUSIC,
    "pilates": _BUILTIN_PILATES,
    "running": _BUILTIN_RUNNING,
    "fat_loss": _BUILTIN_FAT_LOSS,
    "sleep": _BUILTIN_SLEEP,
    "stretching": _BUILTIN_STRETCHING,
    "cooking": _BUILTIN_COOKING,
    "study": _BUILTIN_STUDY,
    "programming": _BUILTIN_PROGRAMMING,
    "finance": _BUILTIN_FINANCE,
    "science": _BUILTIN_SCIENCE,
}

_BUILTIN_ALIASES: Dict[str, str] = {
    "瑜伽": "yoga", "yoga": "yoga", "流瑜伽": "yoga", "阴瑜伽": "yoga",
    "冥想": "meditation", "meditation": "meditation", "静心": "meditation", "内观": "meditation",
    "居家健身": "home_fitness", "家庭健身": "home_fitness", "无器械": "home_fitness", "徒手训练": "home_fitness", "workout": "home_fitness",
    "疗愈音乐": "healing_music", "轻音乐": "healing_music", "助眠音乐": "healing_music", "白噪音": "healing_music", "环境音": "healing_music", "healingmusic": "healing_music",
    "普拉提": "pilates", "pilates": "pilates", "垫上普拉提": "pilates",
    "跑步": "running", "跑步训练": "running", "慢跑": "running", "running": "running", "有氧跑": "running",
    "减脂": "fat_loss", "减脂塑形": "fat_loss", "燃脂": "fat_loss", "瘦身": "fat_loss", "减肥": "fat_loss",
    "睡眠": "sleep", "助眠": "sleep", "睡眠助眠": "sleep", "失眠": "sleep", "睡前放松": "sleep",
    "拉伸": "stretching", "拉伸恢复": "stretching", "恢复训练": "stretching", "筋膜放松": "stretching", "stretch": "stretching",
    "烹饪": "cooking", "食谱": "cooking", "做饭": "cooking", "家常菜": "cooking", "健康饮食": "cooking", "cooking": "cooking",
    "学习": "study", "学习方法": "study", "高效学习": "study", "studywithme": "study", "自习": "study", "时间管理": "study",
    "编程": "programming", "编程开发": "programming", "python": "programming", "前端": "programming", "算法": "programming", "程序员": "programming",
    "财经": "finance", "投资": "finance", "理财": "finance", "基金": "finance", "股票": "finance", "资产配置": "finance",
    "知识": "science", "知识科普": "science", "科普": "science", "泛知识": "science", "社科": "science", "人文": "science", "公开课": "science",
}

_BUILTIN_GENERIC: Dict[str, Any] = {
    "topic": "__generic__",
    "source": "builtin",
    "strong_terms": [],
    "support_terms": [],
    "hard_negative": [],
    "soft_negative": [],
    "slots": [
        {"title": "快速进入", "intent": "先选一个低成本内容进入主题。", "keywords": ["入门", "基础", "概览", "快速"]},
        {"title": "近期重点", "intent": "优先消化最新发布的相关内容。", "keywords": ["最新", "更新", "近期", "重点"]},
        {"title": "方法框架", "intent": "安排偏框架、方法或系统讲解的内容。", "keywords": ["方法", "框架", "体系", "教程"]},
        {"title": "案例观察", "intent": "用案例型内容把主题落到具体对象。", "keywords": ["案例", "复盘", "实操", "拆解"]},
        {"title": "交叉视角", "intent": "放入一个相邻或互补视角。", "keywords": ["对比", "视角", "观点", "经验"]},
        {"title": "深度内容", "intent": "周末留给信息密度更高的内容。", "keywords": ["深度", "完整", "长视频", "详解"]},
        {"title": "回顾补全", "intent": "用一个历史或补充内容收尾。", "keywords": ["总结", "回顾", "补充", "合集"]},
    ],
}


# ---------------------------------------------------------------------------
# TopicProfile data class
# ---------------------------------------------------------------------------

class TopicProfile:
    def __init__(self, data: Dict[str, Any]) -> None:
        self.topic: str = str(data.get("topic") or "")
        self.source: str = str(data.get("source") or "builtin")
        self.strong_terms: List[str] = list(data.get("strong_terms") or [])
        self.support_terms: List[str] = list(data.get("support_terms") or [])
        self.hard_negative: List[str] = list(data.get("hard_negative") or [])
        self.soft_negative: List[str] = list(data.get("soft_negative") or [])
        self.slots: List[Slot] = [
            Slot(
                title=str(s.get("title") or ""),
                intent=str(s.get("intent") or ""),
                keywords=list(s.get("keywords") or []),
            )
            for s in (data.get("slots") or [])
        ]
        self.filter_dimensions: Dict[str, List[Dict[str, Any]]] = data.get("filter_dimensions") or {}
        self.required_space_terms: List[str] = []  # set by apply_filter_dimensions when space constraints detected
        self.generated_at: str = str(data.get("generated_at") or "")

    def to_dict(self) -> Dict[str, Any]:
        return {
            "topic": self.topic,
            "source": self.source,
        "generated_at": self.generated_at,
        "strong_terms": self.strong_terms,
        "support_terms": self.support_terms,
        "hard_negative": self.hard_negative,
        "soft_negative": self.soft_negative,
        "filter_dimensions": self.filter_dimensions,
        "slots": [
            {"title": s.title, "intent": s.intent, "keywords": s.keywords}
            for s in self.slots
            ],
        }

    def needs_filter(self) -> bool:
        """Return True when the profile has enough terms to act as a content gate."""
        return bool(self.strong_terms or self.support_terms)


# ---------------------------------------------------------------------------
# Profile registry / cache
# ---------------------------------------------------------------------------

_MEMORY: Dict[str, TopicProfile] = {}


def _profiles_dir(data_root: Path) -> Path:
    p = data_root / "topic_profiles"
    p.mkdir(parents=True, exist_ok=True)
    return p


def _topic_slug(topic: str) -> str:
    return slugify(topic) or "generic"


def _normalize_topic_key(topic: str) -> str:
    return re.sub(r"[\s_\-/]+", "", topic.strip().lower())


def _find_builtin_profile(topic: str) -> Optional[Dict[str, Any]]:
    key = _normalize_topic_key(topic)
    alias_map = {_normalize_topic_key(alias): profile_key for alias, profile_key in _BUILTIN_ALIASES.items()}
    profile_key = alias_map.get(key)
    if profile_key:
        return _BUILTIN_PROFILES[profile_key]

    for alias, profile_key in sorted(alias_map.items(), key=lambda item: len(item[0]), reverse=True):
        if alias and alias in key:
            return _BUILTIN_PROFILES[profile_key]
    return None


def load_profile(topic: str, data_root: Path, ai_api_key: Optional[str] = None) -> TopicProfile:
    """
    Return a TopicProfile for *topic*.

    Resolution order:
    1. In-memory cache (same process)
    2. Built-in profiles for common Bilibili domains
    3. Cached JSON in data/topic_profiles/<slug>.json
    4. AI-generated (calls OpenAI if api_key supplied)
    5. Falls back to generic profile
    """
    slug = _topic_slug(topic)

    if slug in _MEMORY:
        return _MEMORY[slug]

    # Built-in exact/alias/subtopic match
    builtin_data = _find_builtin_profile(topic)
    if builtin_data:
        profile = TopicProfile({**builtin_data, "topic": topic, "generated_at": ""})
        _MEMORY[slug] = profile
        return profile

    # Cached on disk
    cache_path = _profiles_dir(data_root) / f"{slug}.json"
    if cache_path.exists():
        try:
            data = json.loads(cache_path.read_text(encoding="utf-8"))
            profile = TopicProfile(data)
            _MEMORY[slug] = profile
            return profile
        except (json.JSONDecodeError, KeyError):
            cache_path.unlink(missing_ok=True)

    # AI generation
    if ai_api_key:
        try:
            profile = _generate_via_ai(topic, ai_api_key)
            profile.generated_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
            cache_path.write_text(
                json.dumps(profile.to_dict(), ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
            _MEMORY[slug] = profile
            return profile
        except Exception:
            pass  # fall through to generic

    # Generic fallback
    profile = TopicProfile({**_BUILTIN_GENERIC, "topic": topic})
    _MEMORY[slug] = profile
    return profile


def invalidate_profile(topic: str, data_root: Path) -> None:
    """Delete cached profile so it will be regenerated on next load."""
    slug = _topic_slug(topic)
    _MEMORY.pop(slug, None)
    cache_path = _profiles_dir(data_root) / f"{slug}.json"
    cache_path.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# AI generation
# ---------------------------------------------------------------------------

_SYSTEM_PROMPT = """\
You are a content classification assistant. Given a topic, produce a JSON object
(no markdown fences, raw JSON only) with exactly these fields:

{
  "strong_terms": [...],   // 15-25 terms: strong signals that a video IS practice/tutorial content for this topic
  "support_terms": [...],  // 10-15 softer signals (≥2 needed alongside a topic keyword)
  "hard_negative": [...],  // 5-10 terms: always reject (meta, behind-paywall, stream replays)
  "soft_negative": [...],  // 10-20 terms: reject if in title without a strong signal (vlogs, announcements, etc.)
  "slots": [               // exactly 7 weekly slots, each with title, intent, keywords[]
    {"title": "...", "intent": "...", "keywords": ["..."]}
  ]
}

Rules:
- All terms/keywords must be lowercase.
- Terms should work against concatenated title+description text.
- Slots should form a logical weekly progression for the topic.
- Respond with raw JSON only.
"""


def _generate_via_ai(topic: str, api_key: str) -> TopicProfile:
    """Call OpenAI chat completions to generate a profile for *topic*."""
    base_url = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com").rstrip("/")
    model = os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
    payload = json.dumps({
        "model": model,
        "temperature": 0.3,
        "messages": [
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": f"Topic: {topic}"},
        ],
    }).encode()
    req = urllib.request.Request(
        f"{base_url}/v1/chat/completions",
        data=payload,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        body = json.loads(resp.read().decode())
    content = body["choices"][0]["message"]["content"].strip()
    # Strip markdown fences if present
    content = re.sub(r"^```[a-z]*\n?", "", content)
    content = re.sub(r"\n?```$", "", content)
    data = json.loads(content)
    data["topic"] = topic
    data["source"] = "ai"
    return TopicProfile(data)
